import { Metadata } from "next";
export const metadata: Metadata= {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  
  return <div>
    <h1 className="text-center text-2xl py-20 font-medium ">Welcome to NEXTJS 14 PLYPICKER</h1>
  </div>;
};

export default Home;
