import React, { Suspense } from "react";
import Products from "../_components/Products";
import { Spinner } from "@nextui-org/react";
import { Metadata } from "next";
export const metadata: Metadata= {
  title: "Dashboard",
  description: "Generated by create next app",
};


const Dashboard = () => {
  return (
    <div className="p-4  flex justify-center  ">
      <Suspense
        fallback={
          <Spinner label="Loading products..." color="primary" labelColor="primary" />
        }
      >
        <Products />
      </Suspense>
    </div>
  );
};

export default Dashboard;
