import SubmissionsTable from "@/app/_components/Table/SubmissionsTable";
import { authOptions } from "@/lib/authOptions";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
export const metadata: Metadata= {
  title: "My Submissions",
  description: "Generated by create next app",
};

const SubmissionsPage = async () => {
  const session = await getServerSession(authOptions);
  if (session?.user.role !== "team-member") redirect("/");
  return (
    <div className="p-6">
      <h3 className="text-2xl mb-2">SUBMISSIONS</h3>
      <SubmissionsTable />
    </div>
  );
};

export default SubmissionsPage;
